# Generated by Django 5.2.5 on 2025-08-26 06:26

import api.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                ("admin_id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=50, unique=True)),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
                ("password_hash", models.CharField(max_length=255)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("main_admin", "Main Admin"),
                            ("mart_admin", "Mart Admin"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "admins",
            },
        ),
        migrations.CreateModel(
            name="DeliveryPartner",
            fields=[
                ("partner_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
                (
                    "location_lat",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                (
                    "location_long",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                ("availability", models.BooleanField(default=True)),
                ("approved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "delivery_partners",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                ("order_id", models.AutoField(primary_key=True, serialize=False)),
                ("total_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("shipped", "Shipped"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "orders",
            },
        ),
        migrations.CreateModel(
            name="OTPCode",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("destination", models.CharField(max_length=254)),
                ("code", models.CharField(max_length=10)),
                (
                    "purpose",
                    models.CharField(
                        choices=[("login", "Login"), ("register", "Register")],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField(default=api.models.otp_expires_at)),
                ("used", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "otp_codes",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=50, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password_hash", models.CharField(max_length=255)),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "contact_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "location_lat",
                    models.DecimalField(
                        blank=True,
                        db_index=True,
                        decimal_places=6,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "location_long",
                    models.DecimalField(
                        blank=True,
                        db_index=True,
                        decimal_places=6,
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("preferences", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="AnalyticsLog",
            fields=[
                ("log_id", models.AutoField(primary_key=True, serialize=False)),
                ("action_type", models.CharField(blank=True, max_length=50, null=True)),
                ("details", models.TextField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "admin",
                    models.ForeignKey(
                        blank=True,
                        db_column="admin_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.admin",
                    ),
                ),
            ],
            options={
                "db_table": "analytics_logs",
            },
        ),
        migrations.CreateModel(
            name="Mart",
            fields=[
                ("mart_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                (
                    "location_lat",
                    models.DecimalField(db_index=True, decimal_places=6, max_digits=10),
                ),
                (
                    "location_long",
                    models.DecimalField(db_index=True, decimal_places=6, max_digits=10),
                ),
                ("address", models.TextField(blank=True, null=True)),
                ("approved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "admin",
                    models.OneToOneField(
                        db_column="admin_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.admin",
                    ),
                ),
            ],
            options={
                "db_table": "marts",
            },
        ),
        migrations.CreateModel(
            name="Delivery",
            fields=[
                ("delivery_id", models.AutoField(primary_key=True, serialize=False)),
                ("estimated_time", models.IntegerField(blank=True, null=True)),
                ("actual_time", models.IntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("assigned", "Assigned"),
                            ("in_transit", "In Transit"),
                            ("delivered", "Delivered"),
                        ],
                        default="assigned",
                        max_length=20,
                    ),
                ),
                ("route_data", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "partner",
                    models.ForeignKey(
                        blank=True,
                        db_column="partner_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.deliverypartner",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        db_column="order_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.order",
                    ),
                ),
            ],
            options={
                "db_table": "deliveries",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("product_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("grocery", "Grocery"),
                            ("clothing", "Clothing"),
                            ("essential", "Essential"),
                            ("other", "Other"),
                            ("dairy", "Dairy"),
                        ],
                        max_length=20,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("stock", models.IntegerField(default=0)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "quality_score",
                    models.DecimalField(decimal_places=1, default=0, max_digits=3),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image_url", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "mart",
                    models.ForeignKey(
                        db_column="mart_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.mart",
                    ),
                ),
            ],
            options={
                "db_table": "products",
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                ("item_id", models.AutoField(primary_key=True, serialize=False)),
                ("quantity", models.IntegerField()),
                (
                    "price_at_purchase",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "mart",
                    models.ForeignKey(
                        db_column="mart_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.mart",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        db_column="order_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        db_column="product_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.product",
                    ),
                ),
            ],
            options={
                "db_table": "order_items",
            },
        ),
        migrations.CreateModel(
            name="Offer",
            fields=[
                ("offer_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "discount_percentage",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("description", models.TextField(blank=True, null=True)),
                ("is_global", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mart",
                    models.ForeignKey(
                        blank=True,
                        db_column="mart_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.mart",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        db_column="product_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.product",
                    ),
                ),
            ],
            options={
                "db_table": "offers",
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                ("review_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("comment", models.TextField(blank=True, null=True)),
                ("sentiment_score", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        db_column="product_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.user",
                    ),
                ),
            ],
            options={
                "db_table": "reviews",
            },
        ),
        migrations.AddField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                db_column="user_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="api.user",
            ),
        ),
        migrations.CreateModel(
            name="Basket",
            fields=[
                ("basket_id", models.AutoField(primary_key=True, serialize=False)),
                ("items", models.JSONField()),
                (
                    "optimized_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.user",
                    ),
                ),
            ],
            options={
                "db_table": "baskets",
            },
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                ("address_id", models.AutoField(primary_key=True, serialize=False)),
                ("label", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "contact_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "contact_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("line1", models.CharField(max_length=255)),
                ("line2", models.CharField(blank=True, max_length=255, null=True)),
                ("city", models.CharField(default="Visakhapatnam", max_length=80)),
                ("state", models.CharField(default="Andhra Pradesh", max_length=80)),
                ("pincode", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "location_lat",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                (
                    "location_long",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("instructions", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to="api.user",
                    ),
                ),
            ],
            options={
                "db_table": "addresses",
            },
        ),
        migrations.CreateModel(
            name="UserToken",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "token_key",
                    models.CharField(db_column="token_key", max_length=80, unique=True),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.user",
                    ),
                ),
            ],
            options={
                "db_table": "user_tokens",
            },
        ),
    ]
