# Generated by Django 5.2.5 on 2025-08-26 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mart",
            name="admin",
            field=models.ForeignKey(
                db_column="admin_id",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="marts",
                to="api.admin",
            ),
        ),
    ]
