# Generated by Django 5.2.5 on 2025-08-26 10:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_mart_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="unit_weight_kg",
            field=models.DecimalField(
                decimal_places=3,
                default=1.0,
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="updated_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="deliverypartner",
            name="updated_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
