# Generated by Django 5.2.5 on 2025-08-22 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_usertoken"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="admin",
            options={},
        ),
        migrations.AlterModelOptions(
            name="analyticslog",
            options={},
        ),
        migrations.AlterModelOptions(
            name="basket",
            options={},
        ),
        migrations.AlterModelOptions(
            name="delivery",
            options={},
        ),
        migrations.AlterModelOptions(
            name="deliverypartner",
            options={},
        ),
        migrations.AlterModelOptions(
            name="mart",
            options={},
        ),
        migrations.AlterModelOptions(
            name="offer",
            options={},
        ),
        migrations.AlterModelOptions(
            name="order",
            options={},
        ),
        migrations.AlterModelOptions(
            name="orderitem",
            options={},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={},
        ),
        migrations.AlterModelOptions(
            name="review",
            options={},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
    ]
