# Generated by Django 5.2.5 on 2025-08-26 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_product_unit_weight_kg_alter_delivery_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_address",
            field=models.ForeignKey(
                blank=True,
                db_column="delivery_address_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="api.address",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_address_lat",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_address_long",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_address_snapshot",
            field=models.TextField(blank=True, null=True),
        ),
    ]
