# Generated by Django 5.2.5 on 2025-08-28 18:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_order_delivery_address_order_delivery_address_lat_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="location_lat",
            field=models.DecimalField(
                blank=True, db_index=True, decimal_places=6, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="location_long",
            field=models.DecimalField(
                blank=True, db_index=True, decimal_places=6, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="pincode",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=6,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="PIN code must be a 6-digit number.", regex="^\\d{6}$"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="otpcode",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="otpcode",
            name="purpose",
            field=models.CharField(
                choices=[("login", "Login"), ("register", "Register")],
                default="login",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="usertoken",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="usertoken",
            name="token_key",
            field=models.CharField(db_index=True, max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name="usertoken",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tokens",
                to="api.user",
            ),
        ),
        migrations.AddIndex(
            model_name="address",
            index=models.Index(
                fields=["user", "is_default"], name="addr_user_default_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="address",
            index=models.Index(fields=["pincode"], name="addr_pin_idx"),
        ),
        migrations.AddIndex(
            model_name="address",
            index=models.Index(
                fields=["location_lat", "location_long"], name="addr_loc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mart",
            index=models.Index(
                fields=["location_lat", "location_long"], name="mart_loc_idx"
            ),
        ),
    ]
