# Generated by Django 5.2.5 on 2025-10-21 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_user_is_staff_user_is_superuser_adminauthaudit"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryAgent",
            fields=[
                ("agent_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("password_hash", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "location_lat",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                (
                    "location_long",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "partner",
                    models.ForeignKey(
                        blank=True,
                        db_column="partner_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.deliverypartner",
                    ),
                ),
            ],
            options={
                "db_table": "delivery_agents",
            },
        ),
        migrations.CreateModel(
            name="DeliveryAgentToken",
            fields=[
                ("token_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "token_key",
                    models.CharField(db_index=True, max_length=128, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        db_column="agent_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tokens",
                        to="api.deliveryagent",
                    ),
                ),
            ],
            options={
                "db_table": "delivery_agent_tokens",
            },
        ),
    ]
