# Generated by Django 5.2.5 on 2025-10-26 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_add_deliveryagent_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverypartner",
            name="password_hash",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="deliverypartner",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name="DeliveryPartnerToken",
            fields=[
                ("token_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "token_key",
                    models.CharField(db_index=True, max_length=128, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "partner",
                    models.ForeignKey(
                        db_column="partner_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tokens",
                        to="api.deliverypartner",
                    ),
                ),
            ],
            options={
                "db_table": "delivery_partner_tokens",
            },
        ),
    ]
